import type { Metadata } from "next";
import localFont from "next/font/local";
import { JetBrains_Mono } from "next/font/google";
import "./globals.css";

//components
import Header from "@/components/Header";
import PageTransition from "@/components/PageTransition";

const jetbrains = JetBrains_Mono({
  subsets: ["latin"], 
  weight: ["100", '200', "300", "400", '500', "600", "700", "800"],
  variable: '--font-jetbrains'
});

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${jetbrains.variable}`}>
        <Header />
          <PageTransition>
            {children} {/* Keep children here to render child components */}
          </PageTransition>
      </body>
    </html>
  );
}
